### ISSUE TITLE
<lambda>() takes exactly 1 argument (0 given)

### ISSUE THREAD

**Issue by richardklafter** [lionheart/git-bigstore#20]
The line
```return os.path.join(git_directory(), "bigstore", "objects", hash_function_name)```
calls `git_directory` with no arguments... `git_directory` is defined as 
```git_directory = lambda git_instance: git_instance.rev_parse(git_dir=True)```
and takes one argument.

Am I missing something? Or is the current version broken?

Command:
`git bigstore init .`
Stack Trace:
```
Reading credentials from .bigstore configuration file.
Bigstore has already been initialized.
Traceback (most recent call last):
  File "/usr/local/bin/git-bigstore", line 73, in <module>
    args = parser.parse_args()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1701, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1942, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1898, in consume_positionals
    take_action(action, args)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1807, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1096, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1942, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1898, in consume_positionals
    take_action(action, args)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1807, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/bin/git-bigstore", line 15, in __call__
    init()
  File "/usr/local/lib/python2.7/site-packages/bigstore/bigstore.py", line 449, in init
    mkdir_p(object_directory(default_hash_function_name))
  File "/usr/local/lib/python2.7/site-packages/bigstore/bigstore.py", line 82, in object_directory
    return os.path.join(git_directory(), "bigstore", "objects", hash_function_name)
TypeError: <lambda>() takes exactly 1 argument (0 given)

```

**Comment by richardklafter** [comment]
Using sudo pip install git+git://github.com/lionheart/git-bigstore/@222f0abae37963e7290e636acb749939ea83ab08 for now which seems to work fine

**Comment by dlo** [comment]
@richardklafter Give it another shot from pip--I think this was just an instance of sloppy programming.
