### ISSUE TITLE
How to fix missing note for object

### ISSUE THREAD

**Issue by halfbusy** [lionheart/git-bigstore#49]
After cloning a repo and trying to pull down the assets, `git bigstore pull` is failing with ```stderr: 'error: no note found for object b79a338132ce25ef4bef0b3939f7acbd32adf57c.'```

Perhaps a commit got mangled, or a previous push didn't have the asset make it to S3?

```
git bigstore pull        21:38:15
pulling bigstore metadata...done
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bigstore/bigstore.py", line 327, in pull
    entries = g().notes("--ref=bigstore", "show", sha).split('\n')
  File "/usr/local/lib/python3.7/site-packages/git/cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/lib/python3.7/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git notes --ref=bigstore show b79a338132ce25ef4bef0b3939f7acbd32adf57c
  stderr: 'error: no note found for object b79a338132ce25ef4bef0b3939f7acbd32adf57c.'

During handling of the above exception, another exception occurred:
File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by halfbusy** [comment]
I think this might be a network issue with the remote. Closing for now.
